### ISSUE TITLE
Can't run transcription example

### ISSUE THREAD

**Issue by jacobhq** [floneum/floneum#322]
When I run my code, sourced from https://github.com/floneum/floneum/blob/main/interfaces/kalosm/examples/transcribe.rs and https://floneum.com/kalosm/docs/reference/transcription, no words are transcribed. My microphone definitely works, and I have tried it on a second laptop which also doesn't work. I am not using cuda. Can anyone see what I am doing wrong?
```rust
use kalosm::sound::*;

#[tokio::main]
async fn main() -> Result<(), anyhow::Error> {
    let model = Whisper::builder().build_with_loading_handler(|progress| match progress {
        ModelLoadingProgress::Downloading {
            source,
            start_time,
            progress,
        } => {
            let progress = (progress * 100.0) as u32;
            let elapsed = start_time.elapsed().as_secs_f32();
            println!("Downloading file {source} {progress}% ({elapsed}s)");
        }
        ModelLoadingProgress::Loading { progress } => {
            let progress = (progress * 100.0) as u32;
            println!("Loading model {progress}%");
        }
    })
    .await?;
    println!("1");

    let mic = MicInput::default();
    let stream = mic.stream()?;
    println!("2");

    let mut transcribed = stream.transcribe(model);
    println!("3");
    transcribed.to_std_out().await?;
    println!("4");

    Ok(())
}
```
```
    Finished `dev` profile [unoptimized + debuginfo] target(s) in 0.53s
     Running `target\debug\test.exe`
1
Running on CPU, to run on GPU, build with `--features cuda`
2
3
```
```toml
[package]
name = "test"
version = "0.1.0"
edition = "2021"

[dependencies]
kalosm = { version = "0.3.2", features = ["sound"] }
tokio = { version = "1.43.0", features = ["full"] }
anyhow = "1.0.95"
```
